
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install sphinx
  - pip install sphinx-rtd-theme
# command to run tests
script:
  - cd Documentation
  - make html
